export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const LOAD_USER = 'LOAD_USER'
export const LOAD_FAIL = "LOAD_FAIL"
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const FORGOT = "FORGOT"
export const RESET = "RESET"
export const FORGOT_FAIL = "FORGOT_FAIL"
export const RESET_FAIL = "RESET_FAIL"



//Alert
export const ALERT_FAIL = "ALERT_FAIL"
export const ALERT_SUCCESS = "ALERT_SUCCESS"
export const CLEAR_LOADING = "CLEAR_LOADING"


//post
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAIL = "CREATE_POST_FAIL"
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS"
export const GET_ALL_POST_FAIL = "GET_ALL_POST_FAIL"
export const CLEAR_STATUS = "CLEAR_STATUS"
export const DELETE_POST = "DELETE_POST"
export const DELETE_POST_FAIL = "DELETE_POST_FAIL"
export const GET_SINGLE_POST = "GET_SINGLE_POST"
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL"
export const FILTER_POST_SUCCESS  = "FILTER_POST_SUCCESS"
export const FILTER_POST_FAIL = "FILTER_POST_FAIL"

export const ALL_POSTS = "ALL_POSTS"
export const ALL_POSTS_fAIL = "ALL_POSTS_FAIL"